
services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true

  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - web
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with hot-reloading on Windows/WSL
      - VITE_PROXY_TARGET=http://web:8000

